# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sync_pb2 as sync__pb2


class SyncStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.storeFrame = channel.unary_unary(
        '/personalgram.sync.Sync/storeFrame',
        request_serializer=sync__pb2.StoreRequest.SerializeToString,
        response_deserializer=sync__pb2.StoreResponse.FromString,
        )


class SyncServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def storeFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SyncServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'storeFrame': grpc.unary_unary_rpc_method_handler(
          servicer.storeFrame,
          request_deserializer=sync__pb2.StoreRequest.FromString,
          response_serializer=sync__pb2.StoreResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'personalgram.sync.Sync', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
