# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sync.proto',
  package='personalgram.sync',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nsync.proto\x12\x11personalgram.sync\"\x1d\n\x0cStoreRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\" \n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32W\n\x04Sync\x12O\n\nstoreFrame\x12\x1f.personalgram.sync.StoreRequest\x1a .personalgram.sync.StoreResponseb\x06proto3')
)




_STOREREQUEST = _descriptor.Descriptor(
  name='StoreRequest',
  full_name='personalgram.sync.StoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='personalgram.sync.StoreRequest.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=62,
)


_STORERESPONSE = _descriptor.Descriptor(
  name='StoreResponse',
  full_name='personalgram.sync.StoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='personalgram.sync.StoreResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['StoreRequest'] = _STOREREQUEST
DESCRIPTOR.message_types_by_name['StoreResponse'] = _STORERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreRequest = _reflection.GeneratedProtocolMessageType('StoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREREQUEST,
  '__module__' : 'sync_pb2'
  # @@protoc_insertion_point(class_scope:personalgram.sync.StoreRequest)
  })
_sym_db.RegisterMessage(StoreRequest)

StoreResponse = _reflection.GeneratedProtocolMessageType('StoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORERESPONSE,
  '__module__' : 'sync_pb2'
  # @@protoc_insertion_point(class_scope:personalgram.sync.StoreResponse)
  })
_sym_db.RegisterMessage(StoreResponse)



_SYNC = _descriptor.ServiceDescriptor(
  name='Sync',
  full_name='personalgram.sync.Sync',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='storeFrame',
    full_name='personalgram.sync.Sync.storeFrame',
    index=0,
    containing_service=None,
    input_type=_STOREREQUEST,
    output_type=_STORERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYNC)

DESCRIPTOR.services_by_name['Sync'] = _SYNC

# @@protoc_insertion_point(module_scope)
