application:
  packages:
    camera:
      type: python
      version: 0.1.0
    sync:
      type: python
      version: 0.1.0
    api:
      type: nodejs
      version: 0.1.0
    auth:
      type: python
      version: 0.1.0
  build:
    camera:
      depends: []
    sync:
      depends: ['auth']
    auth:
      depends: []
    