# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import auth_pb2 as auth__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CameraStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.login = channel.unary_unary(
        '/personalgram.auth.Camera/login',
        request_serializer=auth__pb2.AuthRequest.SerializeToString,
        response_deserializer=auth__pb2.AuthResponse.FromString,
        )
    self.logout = channel.unary_unary(
        '/personalgram.auth.Camera/logout',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=auth__pb2.AuthResponse.FromString,
        )
    self.currentUser = channel.unary_unary(
        '/personalgram.auth.Camera/currentUser',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=auth__pb2.AuthResponse.FromString,
        )


class CameraServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def currentUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=auth__pb2.AuthRequest.FromString,
          response_serializer=auth__pb2.AuthResponse.SerializeToString,
      ),
      'logout': grpc.unary_unary_rpc_method_handler(
          servicer.logout,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=auth__pb2.AuthResponse.SerializeToString,
      ),
      'currentUser': grpc.unary_unary_rpc_method_handler(
          servicer.currentUser,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=auth__pb2.AuthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'personalgram.auth.Camera', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
