# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='personalgram.camera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63\x61mera.proto\x12\x13personalgram.camera\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\rFrameResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32P\n\x06\x43\x61mera\x12\x46\n\x08getFrame\x12\x16.google.protobuf.Empty\x1a\".personalgram.camera.FrameResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_FRAMERESPONSE = _descriptor.Descriptor(
  name='FrameResponse',
  full_name='personalgram.camera.FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='personalgram.camera.FrameResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['FrameResponse'] = _FRAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameResponse = _reflection.GeneratedProtocolMessageType('FrameResponse', (_message.Message,), {
  'DESCRIPTOR' : _FRAMERESPONSE,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:personalgram.camera.FrameResponse)
  })
_sym_db.RegisterMessage(FrameResponse)



_CAMERA = _descriptor.ServiceDescriptor(
  name='Camera',
  full_name='personalgram.camera.Camera',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFrame',
    full_name='personalgram.camera.Camera.getFrame',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FRAMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERA)

DESCRIPTOR.services_by_name['Camera'] = _CAMERA

# @@protoc_insertion_point(module_scope)
